# Generated by Django 4.1.2 on 2024-07-01 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('store', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(db_column='id_carrito', primary_key=True, serialize=False)),
                ('subtotal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('id_carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, to='store.carrito')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='store.producto')),
            ],
        ),
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(through='store.CarritoProducto', to='store.producto'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='rut_cliente',
            field=models.ForeignKey(db_column='rut_cliente', on_delete=django.db.models.deletion.CASCADE, to='login.usuario'),
        ),
    ]
