# Generated by Django 4.1.2 on 2024-06-30 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(db_column='id_comuna', primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(db_column='id_region', primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('rut_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pnombre_cliente', models.CharField(max_length=50)),
                ('snombre_cliente', models.CharField(max_length=50)),
                ('apaterno_cliente', models.CharField(max_length=50)),
                ('amaterno_cliente', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.CASCADE, to='login.comuna')),
                ('id_region', models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='login.region')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='login.region'),
        ),
    ]
