# Generated by Django 4.1.2 on 2024-07-10 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rut_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pnombre_cliente', models.CharField(max_length=50)),
                ('snombre_cliente', models.CharField(max_length=50)),
                ('apaterno_cliente', models.CharField(max_length=50)),
                ('amaterno_cliente', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.CASCADE, to='login.comuna')),
                ('id_region', models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='login.region')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
