# Generated by Django 4.1.2 on 2024-07-16 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_cliente_user'),
        ('carrito', '0002_remove_carrito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(db_column='rut_cliente', default=None, on_delete=django.db.models.deletion.CASCADE, to='login.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='talla',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
