# Generated by Django 4.1.2 on 2024-07-17 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_carritoproducto_id_carrito_and_more'),
        ('login', '0003_cliente_user'),
        ('carrito', '0003_carrito_cliente_itemcarrito_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('numero_boleta', models.AutoField(db_column='numero_boleta', primary_key=True, serialize=False)),
                ('subtotal', models.IntegerField()),
                ('iva', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cliente', models.ForeignKey(db_column='rut_cliente', on_delete=django.db.models.deletion.CASCADE, to='login.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBoleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('talla', models.IntegerField()),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito.boleta')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producto')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='productos',
            field=models.ManyToManyField(through='carrito.ProductoBoleta', to='store.producto'),
        ),
    ]
