# Generated by Django 4.1.2 on 2024-07-17 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_boleta_productoboleta_boleta_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
