# Generated by Django 4.1.2 on 2024-07-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_boleta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='iva',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='subtotal',
            field=models.IntegerField(null=True),
        ),
    ]
